apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-nginx-image
spec:
  validationFailureAction: enforce
  rules:
  - name: restrict-nginx-image
    match:
      resources:
        kinds:
        - Deployment
    validate:
      message: "{{ request.object.spec.template.spec.containers[].image }}"
      deny:
        conditions:
          any:
            - key: "{{ request.object.spec.template.spec.containers[].image | contains(@, 'nginx') }}"
              operator: Equals
              value: true